stages:
  - triggers

library:
  stage: triggers
  trigger:
    include: .gitlab/library.yml
    strategy: depend
  rules:
    - if: $CI_COMMIT_TAG =~ /^vue-modals\@.*$/

nuxt:
  stage: triggers
  trigger:
    include: .gitlab/nuxt.yml
    strategy: depend
  rules:
    - if: $CI_COMMIT_TAG =~ /^nuxt-modals\@.*$/

docs:
  stage: triggers
  trigger:
    include: .gitlab/docs.yml
    strategy: depend
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      changes:
        - "docs/**/*"